/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment/index'
import { Route as AuthenticatedEquipmentSnowboardRouteImport } from './routes/_authenticated/equipment/snowboard'
import { Route as AuthenticatedEquipmentSkiRouteImport } from './routes/_authenticated/equipment/ski'
import { Route as AuthenticatedEquipmentHelmetRouteImport } from './routes/_authenticated/equipment/helmet'
import { Route as AuthenticatedEquipmentBootRouteImport } from './routes/_authenticated/equipment/boot'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEquipmentRoute,
  } as any)
const AuthenticatedEquipmentSnowboardRoute =
  AuthenticatedEquipmentSnowboardRouteImport.update({
    id: '/snowboard',
    path: '/snowboard',
    getParentRoute: () => AuthenticatedEquipmentRoute,
  } as any)
const AuthenticatedEquipmentSkiRoute =
  AuthenticatedEquipmentSkiRouteImport.update({
    id: '/ski',
    path: '/ski',
    getParentRoute: () => AuthenticatedEquipmentRoute,
  } as any)
const AuthenticatedEquipmentHelmetRoute =
  AuthenticatedEquipmentHelmetRouteImport.update({
    id: '/helmet',
    path: '/helmet',
    getParentRoute: () => AuthenticatedEquipmentRoute,
  } as any)
const AuthenticatedEquipmentBootRoute =
  AuthenticatedEquipmentBootRouteImport.update({
    id: '/boot',
    path: '/boot',
    getParentRoute: () => AuthenticatedEquipmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRouteWithChildren
  '/equipment/boot': typeof AuthenticatedEquipmentBootRoute
  '/equipment/helmet': typeof AuthenticatedEquipmentHelmetRoute
  '/equipment/ski': typeof AuthenticatedEquipmentSkiRoute
  '/equipment/snowboard': typeof AuthenticatedEquipmentSnowboardRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment/boot': typeof AuthenticatedEquipmentBootRoute
  '/equipment/helmet': typeof AuthenticatedEquipmentHelmetRoute
  '/equipment/ski': typeof AuthenticatedEquipmentSkiRoute
  '/equipment/snowboard': typeof AuthenticatedEquipmentSnowboardRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRouteWithChildren
  '/_authenticated/equipment/boot': typeof AuthenticatedEquipmentBootRoute
  '/_authenticated/equipment/helmet': typeof AuthenticatedEquipmentHelmetRoute
  '/_authenticated/equipment/ski': typeof AuthenticatedEquipmentSkiRoute
  '/_authenticated/equipment/snowboard': typeof AuthenticatedEquipmentSnowboardRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/equipment'
    | '/equipment/boot'
    | '/equipment/helmet'
    | '/equipment/ski'
    | '/equipment/snowboard'
    | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/equipment/boot'
    | '/equipment/helmet'
    | '/equipment/ski'
    | '/equipment/snowboard'
    | '/equipment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment'
    | '/_authenticated/equipment/boot'
    | '/_authenticated/equipment/helmet'
    | '/_authenticated/equipment/ski'
    | '/_authenticated/equipment/snowboard'
    | '/_authenticated/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedEquipmentRoute
    }
    '/_authenticated/equipment/snowboard': {
      id: '/_authenticated/equipment/snowboard'
      path: '/snowboard'
      fullPath: '/equipment/snowboard'
      preLoaderRoute: typeof AuthenticatedEquipmentSnowboardRouteImport
      parentRoute: typeof AuthenticatedEquipmentRoute
    }
    '/_authenticated/equipment/ski': {
      id: '/_authenticated/equipment/ski'
      path: '/ski'
      fullPath: '/equipment/ski'
      preLoaderRoute: typeof AuthenticatedEquipmentSkiRouteImport
      parentRoute: typeof AuthenticatedEquipmentRoute
    }
    '/_authenticated/equipment/helmet': {
      id: '/_authenticated/equipment/helmet'
      path: '/helmet'
      fullPath: '/equipment/helmet'
      preLoaderRoute: typeof AuthenticatedEquipmentHelmetRouteImport
      parentRoute: typeof AuthenticatedEquipmentRoute
    }
    '/_authenticated/equipment/boot': {
      id: '/_authenticated/equipment/boot'
      path: '/boot'
      fullPath: '/equipment/boot'
      preLoaderRoute: typeof AuthenticatedEquipmentBootRouteImport
      parentRoute: typeof AuthenticatedEquipmentRoute
    }
  }
}

interface AuthenticatedEquipmentRouteChildren {
  AuthenticatedEquipmentBootRoute: typeof AuthenticatedEquipmentBootRoute
  AuthenticatedEquipmentHelmetRoute: typeof AuthenticatedEquipmentHelmetRoute
  AuthenticatedEquipmentSkiRoute: typeof AuthenticatedEquipmentSkiRoute
  AuthenticatedEquipmentSnowboardRoute: typeof AuthenticatedEquipmentSnowboardRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
}

const AuthenticatedEquipmentRouteChildren: AuthenticatedEquipmentRouteChildren =
  {
    AuthenticatedEquipmentBootRoute: AuthenticatedEquipmentBootRoute,
    AuthenticatedEquipmentHelmetRoute: AuthenticatedEquipmentHelmetRoute,
    AuthenticatedEquipmentSkiRoute: AuthenticatedEquipmentSkiRoute,
    AuthenticatedEquipmentSnowboardRoute: AuthenticatedEquipmentSnowboardRoute,
    AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
  }

const AuthenticatedEquipmentRouteWithChildren =
  AuthenticatedEquipmentRoute._addFileChildren(
    AuthenticatedEquipmentRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
