/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment/index'
import { Route as AuthenticatedEquipmentSnowboardBootRouteImport } from './routes/_authenticated/equipment/snowboard-boot'
import { Route as AuthenticatedEquipmentSnowboardRouteImport } from './routes/_authenticated/equipment/snowboard'
import { Route as AuthenticatedEquipmentSkiBootRouteImport } from './routes/_authenticated/equipment/ski-boot'
import { Route as AuthenticatedEquipmentSkiRouteImport } from './routes/_authenticated/equipment/ski'
import { Route as AuthenticatedEquipmentHelmetRouteImport } from './routes/_authenticated/equipment/helmet'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentSnowboardBootRoute =
  AuthenticatedEquipmentSnowboardBootRouteImport.update({
    id: '/equipment/snowboard-boot',
    path: '/equipment/snowboard-boot',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentSnowboardRoute =
  AuthenticatedEquipmentSnowboardRouteImport.update({
    id: '/equipment/snowboard',
    path: '/equipment/snowboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentSkiBootRoute =
  AuthenticatedEquipmentSkiBootRouteImport.update({
    id: '/equipment/ski-boot',
    path: '/equipment/ski-boot',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentSkiRoute =
  AuthenticatedEquipmentSkiRouteImport.update({
    id: '/equipment/ski',
    path: '/equipment/ski',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentHelmetRoute =
  AuthenticatedEquipmentHelmetRouteImport.update({
    id: '/equipment/helmet',
    path: '/equipment/helmet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment/helmet': typeof AuthenticatedEquipmentHelmetRoute
  '/equipment/ski': typeof AuthenticatedEquipmentSkiRoute
  '/equipment/ski-boot': typeof AuthenticatedEquipmentSkiBootRoute
  '/equipment/snowboard': typeof AuthenticatedEquipmentSnowboardRoute
  '/equipment/snowboard-boot': typeof AuthenticatedEquipmentSnowboardBootRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment/helmet': typeof AuthenticatedEquipmentHelmetRoute
  '/equipment/ski': typeof AuthenticatedEquipmentSkiRoute
  '/equipment/ski-boot': typeof AuthenticatedEquipmentSkiBootRoute
  '/equipment/snowboard': typeof AuthenticatedEquipmentSnowboardRoute
  '/equipment/snowboard-boot': typeof AuthenticatedEquipmentSnowboardBootRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment/helmet': typeof AuthenticatedEquipmentHelmetRoute
  '/_authenticated/equipment/ski': typeof AuthenticatedEquipmentSkiRoute
  '/_authenticated/equipment/ski-boot': typeof AuthenticatedEquipmentSkiBootRoute
  '/_authenticated/equipment/snowboard': typeof AuthenticatedEquipmentSnowboardRoute
  '/_authenticated/equipment/snowboard-boot': typeof AuthenticatedEquipmentSnowboardBootRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/equipment/helmet'
    | '/equipment/ski'
    | '/equipment/ski-boot'
    | '/equipment/snowboard'
    | '/equipment/snowboard-boot'
    | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/equipment/helmet'
    | '/equipment/ski'
    | '/equipment/ski-boot'
    | '/equipment/snowboard'
    | '/equipment/snowboard-boot'
    | '/equipment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment/helmet'
    | '/_authenticated/equipment/ski'
    | '/_authenticated/equipment/ski-boot'
    | '/_authenticated/equipment/snowboard'
    | '/_authenticated/equipment/snowboard-boot'
    | '/_authenticated/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/snowboard-boot': {
      id: '/_authenticated/equipment/snowboard-boot'
      path: '/equipment/snowboard-boot'
      fullPath: '/equipment/snowboard-boot'
      preLoaderRoute: typeof AuthenticatedEquipmentSnowboardBootRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/snowboard': {
      id: '/_authenticated/equipment/snowboard'
      path: '/equipment/snowboard'
      fullPath: '/equipment/snowboard'
      preLoaderRoute: typeof AuthenticatedEquipmentSnowboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/ski-boot': {
      id: '/_authenticated/equipment/ski-boot'
      path: '/equipment/ski-boot'
      fullPath: '/equipment/ski-boot'
      preLoaderRoute: typeof AuthenticatedEquipmentSkiBootRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/ski': {
      id: '/_authenticated/equipment/ski'
      path: '/equipment/ski'
      fullPath: '/equipment/ski'
      preLoaderRoute: typeof AuthenticatedEquipmentSkiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/helmet': {
      id: '/_authenticated/equipment/helmet'
      path: '/equipment/helmet'
      fullPath: '/equipment/helmet'
      preLoaderRoute: typeof AuthenticatedEquipmentHelmetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentHelmetRoute: typeof AuthenticatedEquipmentHelmetRoute
  AuthenticatedEquipmentSkiRoute: typeof AuthenticatedEquipmentSkiRoute
  AuthenticatedEquipmentSkiBootRoute: typeof AuthenticatedEquipmentSkiBootRoute
  AuthenticatedEquipmentSnowboardRoute: typeof AuthenticatedEquipmentSnowboardRoute
  AuthenticatedEquipmentSnowboardBootRoute: typeof AuthenticatedEquipmentSnowboardBootRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentHelmetRoute: AuthenticatedEquipmentHelmetRoute,
  AuthenticatedEquipmentSkiRoute: AuthenticatedEquipmentSkiRoute,
  AuthenticatedEquipmentSkiBootRoute: AuthenticatedEquipmentSkiBootRoute,
  AuthenticatedEquipmentSnowboardRoute: AuthenticatedEquipmentSnowboardRoute,
  AuthenticatedEquipmentSnowboardBootRoute:
    AuthenticatedEquipmentSnowboardBootRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
